name: ci

on:
  pull_request:
    branches: [master]

jobs:
  test-app:
    name: Build & Test App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install API dependencies
        run: |
          cd eventp-api
          npm install

      - name: Build React app
        run: npm run build

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      
      - name: Build and run all docker containers
        run: docker-compose up --build -d