name: ci

on:
  pull_request:
    branches: [master]

jobs:
  test-app:
    name: Build & Test App
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: eventp
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Build database
        run: |
          export PGPASSWORD=password
          cd eventp-api
          psql -U postgres -d eventp -h localhost -f ./resources/db-delete.sql
          psql -U postgres -d eventp -h localhost -f ./resources/db-create.sql
          psql -U postgres -d eventp -h localhost -f ./resources/db-insert.sql

      - name: Install API dependencies
        run: |
          cd eventp-api
          npm install

      - name: Build React app
        run: npm run build